### ISSUE TITLE
Hooks are not properly injected

### ISSUE THREAD

**Issue by zvonkok** [cncf-tags/container-device-interface-rs#28]
Hooks are not properly injected. There are global edits and local edits for the device. It looks like that Hooks are applied with the first round of edits but deleted by the second round of applying the containeredits merge.

```
---
cdiVersion: 0.5.0
containerEdits:
  env:
  - NVIDIA_VISIBLE_DEVICES=void
  hooks:
  - args:
    - nvidia-ctk
    - hook
    - update-ldcache
    - --folder
    - /ib/x86_64-linux-gnu
    hookName: createContainer
    path: /bin/nvidia-ctk
devices:
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/39
  name: "0"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/78
  name: "1"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/90
  name: "2"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/102
  name: "3"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/288
  name: "4"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/327
  name: "5"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/339
  name: "6"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/351
  name: "7"
kind: nvidia.com/pgpu

```
